version = 0.1

[default.deploy.parameters]
stack_name = "leadsentry"
resolve_s3 = true
s3_prefix = "leadsentry"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DemoMode=\"true\""
image_repositories = []

[default.global.parameters]
region = "us-east-1"
